SUPABASE_URL = "https://wktgkcqrogppvktalmzq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdGdrY3Fyb2dwcHZrdGFsbXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTA5NDMsImV4cCI6MjA2NzE2Njk0M30.l-0oBYsbkAy3u3EejSsT0Au_P5A7MuCny2E3zxiR3Q0"
OPENAI_API_KEY = "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"
